### ISSUE TITLE
Bug: server list is not working

### ISSUE THREAD

**Issue by louanfontenele** [DarkGuy10/BotClient#48] opened 2022-12-03 20:24 UTC
### Issue checklist

- [X] I have checked the FAQs.
- [X] I have searched the existing issues to make sure this isn't a duplicate.
- [X] I have discussed this issue on the support server.

### Issue description

server list is not working
![image](https://user-images.githubusercontent.com/2886066/205460461-22c1f2b9-adf4-4cee-83c1-ff4f91ce2c0e.png)

### BotClient version

v0.10.3-alpha

### Operating System

Windows 11

### How did you download the application?

From GitHub releases (or links from the readme)

### Priority this issue should have

High (immediate attention needed)

**Comment by DarkGuy10** [comment] 2022-12-11 08:19
Closing as duplicate of #46

**Closed by DarkGuy10** 2022-12-11 08:19 UTC
Labels: Bug: Unverified
