### ISSUE TITLE
Bug: Channels don't load successfully

### ISSUE THREAD

**Issue by TheRedstoneRadiant** [DarkGuy10/BotClient#46] opened 2022-10-05 06:44 UTC
### Issue checklist

- [X] I have checked the FAQs.
- [X] I have searched the existing issues to make sure this isn't a duplicate.
- [x] I have discussed this issue on the support server.

### Issue description

Steps to reproduce the bug:
1. Go to a server with Thread channels

### Current behavior

Channels don't load and an error message appears in the console
[1] Error occurred in handler for 'channels': TypeError: Cannot read properties of null (reading 'has')
[1]     at serializeGuildChannel (.../BotClient/public/serializers/serializeGuildChannel.js:19:4)
[1]     at /home/user/Downloads/BotClient/public/electron.js:153:3
[1]     at Array.map (<anonymous>)
[1]     at /home/user/Downloads/BotClient/public/electron.js:152:61
[1]     at node:electron/js2c/browser_init:189:579
[1]     at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11093)
[1]     at EventEmitter.emit (node:events:390:28)

### Expected behavior

Non thread channels should display

### BotClient version

v0.10.3-alpha

### Operating System

Solus Linux

### How did you download the application?

Built from source

### Priority this issue should have

Medium (should be fixed soon)

**Comment by Aeris1One** [comment] 2022-11-12 20:46
can reproduce

**Comment by aiko-chan-ai** [comment] 2022-12-18 11:20
@DarkGuy10 problem caused by discord.js v13, it will be resolved after [it](https://github.com/discordjs/discord.js/pull/8651) is merged

**Comment by PlavorSeol** [comment] 2023-03-03 12:48
For anyone experiencing this bug:
Applying changes from #49 manually and building from source yourself will fix it for now.

**Closed** 2023-03-19 13:00 UTC
Labels: Bug: Confirmed, Priority: High
